###
GET http://localhost:8080/

### home
GET http://localhost:8080/home

###
GET http://localhost:8080/login

###
GET http://localhost:8080/loginForm?userId=swiftly&userPass=askldj09fu0iof

###
GET http://localhost:8080/insertProc?id=12312&firstName=brown&lastName=hair